[package]
name = "botfaz2077"
version = "0.1.0"
authors = ["DarthFaz2077"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.9.0-rc.1"
env_logger = "0.6"
kankyo = "0.2"
log = "0.4"
tokio = { version = "0.2", features = ["macros"]}
