[package]
name = "botfaz2077"
version = "0.1.0"
authors = ["DarthFaz2077"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.9.0-rc.2"
kankyo = "0.2"
tokio = { version = "0.2", features = ["macros"]}
reqwest = { version = "0.10", features = ["json"] }
serde = "1.0.116"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"

[target.'cfg(linux)'.dependencies.openssl]
version = "0.10"
features = ["vendored"]
