[package]
name = "botfaz2077"
version = "0.1.1"
authors = ["DarthFaz2077"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.10.4"
dotenv = "0.15.0"
tokio = { version = "1.3.0", features = ["macros", "rt-multi-thread"]}
reqwest = { version = "0.11.2", features = ["json"] }
serde = "1.0.124"
tracing = "0.1.25"
tracing-subscriber = "0.2.16"
tracing-futures = "0.2.5"
