[package]
name = "botfaz2077"
version = "0.1.0"
authors = ["DarthFaz2077"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.9.4"
kankyo = "0.2.0"
tokio = { version = "0.2.22", features = ["macros"]}
reqwest = { version = "0.10.8", features = ["json"] }
serde = "1.0.120"
tracing = "0.1.22"
tracing-subscriber = "0.2.15"
tracing-futures = "0.2.4"
