[package]
name = "botfaz2077"
version = "0.1.1"
authors = ["DarthFaz2077"]
edition = "2018"

[dependencies]
serenity = "0.10.4"
tokio = { version = "1.4.0", features = ["macros", "rt-multi-thread"] }
reqwest = { version = "0.11.2", features = ["json"] }
serde = { version = "1.0.124", features = ["derive"] }
tracing = "0.1.25"
tracing-subscriber = "0.2.17"
tracing-futures = "0.2.5"
envy = "0.4.2"
humantime = "2.1.0"
blake3 = "0.3.7"
chrono = "0.4.19"
mongodb = "2.0.0-alpha"
