name: Daily Deploy

on:
  schedule:
    - cron: "0 3 * * *"

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Delete old binary
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: rm -rf ~/BotFaz2077/botfaz2077

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2.9.0
        with:
          workflow: push.yml
          branch: master
          name: botfaz2077
          path: Botfaz2077

      - name: Upload new binary
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: BotFaz2077/botfaz2077
          target: BotFaz2077
          strip_components: 1

      - name: Restart bot
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: sudo systemctl restart botfaz2077.service
