name: Check Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  pull_request:
    name: Pull Request

    runs-on: ubuntu-latest

    steps:
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.1.1

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2.3.0
        with:
          tags: darthfaz2077/botfaz2077:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
