name: Check Pull Request

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  pull_request:
    name: Pull Request

    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.3.4

      - name: Cache Deps
        uses: actions/cache@v2.1.3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache toolchain
        uses: actions/cache@v2.1.3
        with:
          path: |
            ~/.rustup/toolchains
            ~/.rustup/update-hashes
            ~/.rustup/settings.toml
          key: toolchain

      - name: Install toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          override: true

      - name: Compile
        uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --release
