name: Compile and Upload Push

on:
  push:
    branches:
      - master

jobs:
  push:
    name: Push

    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.3.3

      - name: Cache Deps
        uses: actions/cache@v2.1.2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache toolchain
        uses: actions/cache@v2.1.2
        with:
          path: |
            ~/.rustup/toolchains
            ~/.rustup/update-hashes
            ~/.rustup/settings.toml
          key: toolchain

      - name: Install toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          override: true

      - name: Compile
        uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --release

      - name: Tar binary
        run: tar -cvf botfaz2077.tar target/release/botfaz2077

      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: botfaz2077.tar
          path: botfaz2077.tar
