name: Build and push new version to DockerHub

on:
  push:
    branches:
      - main

jobs:
  push:
    name: Push

    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.1.1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.3.0
        with:
          push: true
          tags: darthfaz2077/botfaz2077:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
