name: Upload Release Binaries

on:
  release:
    types:
      - published

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.3.4

      - name: Cache Deps
        uses: actions/cache@v2.1.3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache toolchain
        uses: actions/cache@v2.1.3
        with:
          path: |
            ~/.rustup/toolchains
            ~/.rustup/update-hashes
            ~/.rustup/settings.toml
          key: toolchain

      - name: Install toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          override: true

      - name: Compile
        uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --release

      - name: Upload Linux binary
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/release/botfaz2077
          asset_name: botfaz2077
          asset_content_type: application/octet-stream
