name: Daily Security Audit
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  audit:
    name: Security Audit

    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.3.4

      - name: Audit check
        uses: actions-rs/audit-check@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
